# Generated by Django 3.1 on 2020-11-11 07:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.TextField(default='')),
                ('is_reward', models.BooleanField(default=False)),
                ('name', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('found_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('img', models.ImageField(blank=True, upload_to='lostitems')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='place',
        ),
        migrations.AddField(
            model_name='user',
            name='mailining',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='FoundItem',
        ),
        migrations.DeleteModel(
            name='LostItem',
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='item',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.place'),
        ),
    ]
