# Generated by Django 3.1 on 2020-11-11 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201111_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mailining',
            new_name='mailing',
        ),
    ]
