# Generated by Django 3.1 on 2020-11-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201118_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_date',
            new_name='date',
        ),
    ]
