# Generated by Django 3.1 on 2020-11-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201118_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.TextField(default=''),
        ),
    ]
