# Generated by Django 3.0.4 on 2020-11-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.FileField(blank=True, upload_to='items_documents'),
        ),
    ]
