# Generated by Django 3.0.4 on 2020-11-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201119_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchased_items',
            field=models.ManyToManyField(blank=True, null=True, to='api.Purchased_Item'),
        ),
    ]
