# Generated by Django 3.0.4 on 2020-11-20 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201120_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Condition'),
        ),
    ]
