# Generated by Django 3.0.4 on 2020-11-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_itemtobuy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtobuy',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='itemtobuy',
            name='receive_date',
        ),
        migrations.AlterField(
            model_name='itemtobuy',
            name='image',
            field=models.ImageField(blank=True, upload_to='items_to_buy_images'),
        ),
    ]
