# Generated by Django 3.0.4 on 2020-11-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201124_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtobuy',
            name='address',
        ),
    ]
