# Generated by Django 3.0.4 on 2020-11-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_itemtobuy_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtobuy',
            name='count',
        ),
    ]
