# Generated by Django 3.0.4 on 2020-11-24 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_itemtobuy_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased_item',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ItemToBuy'),
        ),
    ]
