# Generated by Django 3.0.4 on 2020-11-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20201124_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='items_documents'),
        ),
    ]
