# Generated by Django 3.0.4 on 2020-11-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20201124_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='address',
        ),
        migrations.AddField(
            model_name='item',
            name='rfid',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='client_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='purchased_item',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
