# Generated by Django 3.0.4 on 2020-11-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20201126_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='order_date',
        ),
    ]
