# Generated by Django 3.0.4 on 2020-12-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20201127_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtobuy',
            name='weight',
        ),
        migrations.AddField(
            model_name='itemtobuy',
            name='url_name',
            field=models.TextField(default=''),
        ),
    ]
