# Generated by Django 3.0.4 on 2020-12-13 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
