# Generated by Django 3.0.4 on 2020-12-13 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20201213_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.TextField(default='')),
                ('port', models.TextField(default='')),
                ('database_name', models.TextField(default='')),
                ('user', models.TextField(default='')),
                ('password', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='provider',
            name='database_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.DatabaseConnection'),
        ),
    ]
