# Generated by Django 3.0.4 on 2020-12-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20201213_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='company_name',
            field=models.TextField(default=''),
        ),
    ]
