# Generated by Django 3.0.4 on 2020-12-20 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_order_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databaseconnection',
            old_name='user',
            new_name='login',
        ),
        migrations.AddField(
            model_name='user',
            name='database_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.DatabaseConnection'),
        ),
        migrations.AlterField(
            model_name='item',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AlterField(
            model_name='itemtobuy',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
