# Generated by Django 3.0.4 on 2020-12-22 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20201220_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='purchase_start_date',
            new_name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_end_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
        migrations.AddField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Company'),
            preserve_default=False,
        ),
    ]
