# Generated by Django 3.0.4 on 2020-12-22 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20201222_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
    ]
