# Generated by Django 3.0.4 on 2020-12-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20201222_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
