# Generated by Django 3.0.4 on 2020-12-22 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20201222_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchased_items',
            field=models.ManyToManyField(blank=True, null=True, to='api.Item'),
        ),
    ]
