# Generated by Django 3.0.4 on 2020-12-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20201222_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchased_items',
            field=models.ManyToManyField(blank=True, null=True, to='api.Purchased_Item'),
        ),
    ]
