# Generated by Django 3.0.4 on 2020-12-22 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20201222_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchased_item',
            name='user',
        ),
    ]
