# Generated by Django 3.0.4 on 2020-12-23 03:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_remove_purchased_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased_item',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(default=datetime.date(2020, 12, 23)),
        ),
    ]
